const data = {
    products: [{
        id:0,
        title:"5,000 Awesome Facts (about Everything!)",
        author:"National Kids",
        category:"childern",
        image:"https://images.bwbcovers.com/142/9781426310492.jpg",
        price:12.61,
    },
    {
        id:1,
        title:"Big First Grade",
        author:"School Zone Publishing Company Staff",
        category:"children",
        image:"https://images.bwbcovers.com/088/Color-Big-Get-Ready-Books-9780887431470.jpg",
        price:21.54,
    },
    {
        id:12,
        title:"Spy School",
        author:"Stuart Gibbs",
        category:"children",
        image:"https://images.bwbcovers.com/144/9781442421837.jpg",
        price:6.24,
    },
    {
        id:2,
        title:"Hello, Baby Animals",
        author:"Duopress, Julissa Mora",
        category:"children",
        image:"https://images.bwbcovers.com/193/9781938093685.jpg",
        price:13.48,
    },
    {
        id:3,
        title:"Brain Quest Workbook: 5th Grade",
        author:"Bridget Heos, Matt Rockefeller",
        category:"children",
        image:"https://images.bwbcovers.com/076/9780761182788.jpg",
        price:22.65,
    },
    {
        id:14,
        title:"First 100 Animals",
        author:"Roger Priddy",
        category:"children",
        image:"https://images.bwbcovers.com/031/9780312510794.jpg",
        price:13.86,
    },
    {
        id:5,
        title:"National Geographic Kids Look and Learn: Farm Animals",
        author:"National Kids",
        category:"children",
        image:"https://images.bwbcovers.com/142/9781426323072.jpg",
        price:14.23,
    },
    {
        id:6,
        title:"Wherever You Are",
        author:"Nancy Tillman",
        category:"children",
        image:"https://images.bwbcovers.com/125/Wherever-You-Are-Tillman-Nancy-9781250017970.jpg",
        price:6.89,
    },
    {
        id:7,
        title:"I Love You Through and Through",
        author:"Caroline Jayne Church, Bernadette Rossetti-Shustak",
        category:"children",
        image:"https://images.bwbcovers.com/043/I-Love-You-Through-and-Through-9780439673631.jpg",
        price:6.82,
    },
    {
        id:8,
        title:"Wish",
        author:"Barbara O'Connor",
        category:"children",
        image:"https://images.bwbcovers.com/125/9781250144058.jpg",
        price:6.79,
    },
    {
        id:9,
        title:"So Much!",
        author:"Trish Cooke, Helen Oxenbury",
        category:"children",
        image:"https://images.bwbcovers.com/076/So-Much-9780763640910.jpg",
        price:8.39,
    },{
        id:10,
        title:"Hug",
        author:"Jez Alborough",
        category:"children",
        image:"https://images.bwbcovers.com/076/Hug-9780763615765.jpg",
        price:13.55,
    },
    {
        id:11,
        title:"Guess How Much I Love You",
        author:"Anita Jeram, Sam McBratney",
        category:"children",
        image:"https://images.bwbcovers.com/153/9781536210637.jpg",
        price:13.10,
    },
    {
        id:13,
        title:"Who Was King Tut?",
        author:"Roberta Edwards, True Kelley, Who HQ",
        category:"history",
        image:"https://images.bwbcovers.com/044/Who-Was-King-Tut-9780448443607.jpg",
        price:5.88,
    },
    {
        id:4,
        title:"Killing the Rising Sun ",
        author:"Martin Dugard, Bill O'Reilly",
        category:"history",
        image:"https://images.bwbcovers.com/162/9781627790628.jpg",
        price:9.25,
    },
    {
        id:15,
        title:"The Penguin History of the World : Sixth Edition",
        author:"J. M. Roberts, Odd Arne Westad",
        category:"history",
        image:"https://images.bwbcovers.com/184/The-Penguin-History-of-the-World-Roberts-J-M-9781846144431.jpg",
        price:14.17,
    },
    {
        id:16,
        title:"Mankind : The Story of All of Us",
        author:"Pamela D. Toler",
        category:"history",
        image:"https://images.bwbcovers.com/076/Mankind-Toler-Ph-D-Pamela-9780762447039.jpg",
        price:13.13,
    },
    {
        id:17,
        title:"The Civil War",
        author:"Julius Caesar, Jane P. Gardner",
        category:"history",
        image:"https://images.bwbcovers.com/014/The-Civil-War-Caesar-Julius-9780140441871.jpg",
        price:6.67,
    },
    {
        id:18,
        title:"1812 : The War That Forged a Nation",
        author:"Walter R. Borneman",
        category:"history",
        image:"https://images.bwbcovers.com/006/1812-Borneman-Walter-R-9780060531133.jpg",
        price:6.64,
    },
    {
        id:19,
        title:"A Brief History of the Samurai",
        author:"Jonathan Clements",
        category:"history",
        image:"https://images.bwbcovers.com/184/A-Brief-History-of-the-Samurai-Clements-Jonathan-9781845299477.jpg",
        price:12.71,
    },
    {
        id:20,
        title:"Genghis Khan",
        author:"John Man",
        category:"history",
        image:"https://images.bwbcovers.com/055/Genghis-Khan-Man-John-9780553814989.jpg",
        price:13.33,
    },]}
    export default data;
    